<?php

namespace Tests\Feature\Account;

use App\Livewire\Account\HistoryAccount;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class HistoryAccountTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            "email" => "test@test.com"
        ]);
    }
    public function test_render_history_account()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(HistoryAccount::class);

        $response->assertStatus(200);
    }
}
