<?php

namespace Tests\Feature\Account;

use App\Livewire\Account\HistoryLogin;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class HistoryLoginTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            'email' => 'test@test.com',
        ]);
    }

    public function test_render_history_login()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(HistoryLogin::class);

        $response->assertStatus(200);
    }
}
