<?php

namespace Tests\Feature\Services;

use App\Livewire\Service\AccessList;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class AccessListTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            "email" => "test@test.com"
        ]);
    }

    public function test_render_access_list()
    {
        Livewire::actingAs($this->user)
            ->test(AccessList::class)
            ->assertStatus(200);
    }
}
