<?php

namespace Auth;

use App\Livewire\Auth\PasswordConfirmation;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class ForgotConfirmationTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            'email' => 'test@test.com',
        ]);
    }

    public function test_render_confirmation_password_page()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(PasswordConfirmation::class);

        $response->assertStatus(200);
    }

    public function test_confirm_password()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(PasswordConfirmation::class)
            ->set('password', 'password')
            ->call('confirm');

        $response->assertStatus(200);
    }

    public function test_confirm_password_is_error()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(PasswordConfirmation::class)
            ->set('password', '0000')
            ->call('confirm');

        $response->assertStatus(200);
    }
}
