<?php

namespace Tests\Feature\Auth;

use App\Livewire\Auth\ForgotPassword;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class ForgotPasswordTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            'email' => 'test@test.com',
        ]);
    }

    public function test_render_forgot_password_page()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(ForgotPassword::class);

        $response->assertStatus(200);
    }

    public function test_change_password()
    {
        $this->withoutExceptionHandling();

        $response = Livewire::actingAs($this->user)
            ->test(ForgotPassword::class)
            ->set('email', 'test@test.com')
            ->call('send');

        $response->assertStatus(200);
    }
}
