<?php

namespace Tests\Feature\Railway;

use App\Livewire\Admin\Railway\Config\ConfigList;
use App\Models\Railway\RailwaySetting;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class RailwayConfigTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            'admin' => true,
        ]);
    }

    public function test_rendering()
    {
        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->assertStatus(200);
    }

    public function test_adding_config_successful()
    {
        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->set('name', 'test')
            ->set('value', 0)
            ->call('adding')
            ->assertHasNoErrors()
            ->assertSee('test');
    }

    public function test_adding_config_required_field()
    {
        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->set('name', '')
            ->set('value', '')
            ->call('adding')
            ->assertHasErrors(['name' => 'required', 'value' => 'required']);
    }

    public function test_show_editing_form()
    {
        $config = RailwaySetting::create([
            'name' => 'test',
            'value' => 0,
        ]);

        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->call('startEdit', $config->id)
            ->assertSet('editId', $config->id);
    }

    public function test_editing_config_successful()
    {
        $config = RailwaySetting::create([
            'name' => 'test',
            'value' => 0,
        ]);

        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->call('startEdit', $config->id)
            ->set('name', 'test2')
            ->set('value', 1)
            ->call('editing', $config->id)
            ->assertHasNoErrors()
            ->assertSee('test2');
    }

    public function test_editing_config_required_field()
    {
        $config = RailwaySetting::create([
            'name' => 'test',
            'value' => 0,
        ]);

        Livewire::actingAs($this->user)
            ->test(ConfigList::class)
            ->call('startEdit', $config->id)
            ->set('name', '')
            ->set('value', '')
            ->call('editing', $config->id)
            ->assertHasErrors(['name' => 'required', 'value' => 'required']);
    }
}
