<?php

namespace Railway;

use App\Livewire\Admin\Railway\Cards\CardModal;
use App\Livewire\Admin\Railway\Cards\CardsList;
use App\Models\Railway\Engine;
use App\Models\Railway\RailwayAdvantageCard;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Livewire\Livewire;
use Tests\TestCase;

class RailwayAdvantageCardTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            "admin" => true,
        ]);
    }

    public function test_railway_save_advantage_card()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        Livewire::test(CardModal::class)
            ->set('form.type', 'argent')
            ->set('form.class', 'third')
            ->set('form.qte', 1)
            ->set('form.tpoint_cost', 1)
            ->call('save');

        $this->assertEquals(1, RailwayAdvantageCard::count());
    }

    public function test_railway_update_advantage_card()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        $card = RailwayAdvantageCard::factory()->create([
            "type" => "argent",
            "class" => "third",
        ]);

        Livewire::test(CardModal::class, ['card' => $card])
            ->set('form.type', 'argent')
            ->set('form.class', 'third')
            ->set('form.qte', 50000)
            ->set('form.tpoint_cost', 10)
            ->call('save');

        $this->assertEquals(1, RailwayAdvantageCard::count());
        $this->assertEquals('argent', RailwayAdvantageCard::first()->type);
        $this->assertEquals(50000, RailwayAdvantageCard::first()->qte);
        $this->assertEquals(10, RailwayAdvantageCard::first()->tpoint_cost);
    }

    public function test_railway_generate_card_by_console()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        Engine::factory()->createMany(5);

        Artisan::call('create', ["action" => "cards"]);

        $this->assertEquals(251, RailwayAdvantageCard::count());
    }

    public function test_railway_unsave_card_cause_required_field()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        Livewire::test(CardModal::class)
            ->set('form.type', 'argent')
            ->set('form.class', 'third')
            ->set('form.qte', 1)
            ->set('form.tpoint_cost', 1)
            ->call('save');

        $this->assertEquals(1, RailwayAdvantageCard::count());

        Livewire::test(CardModal::class)
            ->set('form.type', '')
            ->set('form.class', 'third')
            ->set('form.qte', 1)
            ->set('form.tpoint_cost', 1)
            ->call('save')
            ->assertHasErrors(['type' => 'required']);
    }

    public function test_render_card()
    {
        RailwayAdvantageCard::factory()->create([
            "type" => "argent",
            "class" => "third",
        ]);

        Livewire::actingAs($this->user)
            ->test(CardsList::class)
            ->assertStatus(200)
            ->assertSee('Troisième classe');
    }

    public function test_refresh_list()
    {
        $response = Livewire::actingAs($this->user)
            ->test(CardsList::class)
            ->assertStatus(200);

        Engine::factory(rand(1,10))->create();
        RailwayAdvantageCard::factory()->create([
            "type" => "argent",
            "class" => "third",
        ]);

        $response->call('refresh')
            ->assertSee('Troisième classe');
    }

    public function test_adding_manual_card()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        Livewire::actingAs($this->user)
            ->test(CardsList::class)
            ->assertStatus(200)
            ->set('type', 'argent')
            ->set('class', 'third')
            ->set('qte', 1)
            ->set('tpoint_cost', 1)
            ->call('adding')
            ->assertStatus(200);

        $this->assertEquals(1, RailwayAdvantageCard::count());
    }

    public function test_adding_manual_card_cause_required_field()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        Livewire::actingAs($this->user)
            ->test(CardsList::class)
            ->assertStatus(200)
            ->set('type', '')
            ->set('class', 'third')
            ->set('qte', 1)
            ->set('tpoint_cost', 1)
            ->call('adding')
            ->assertHasErrors(['type' => 'required']);
    }

    public function test_remove_card()
    {
        $this->assertEquals(0, RailwayAdvantageCard::count());

        $card = RailwayAdvantageCard::factory()->create([
            "type" => "argent",
            "class" => "third",
        ]);

        Livewire::actingAs($this->user)
            ->test(CardsList::class)
            ->assertStatus(200)
            ->call('delete', $card->id)
            ->assertStatus(200);

        $this->assertEquals(0, RailwayAdvantageCard::count());
    }
}
