<?php

namespace Tests\Feature\Railway;

use App\Livewire\Admin\Railway\Bonus\BonusList;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class RailwayBonusTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Model::unsetEventDispatcher();
        Model::flushEventListeners();
        $this->user = User::factory()->create([
            'admin' => true,
        ]);
    }

    public function test_rendering()
    {
        $this->artisan('action', ['action' => 'monthly_bonus']);

        $this->assertDatabaseCount('railway_bonuses', 30);

        Livewire::actingAs($this->user)
            ->test(BonusList::class)
            ->assertStatus(200);
    }
}
