name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Mise en cache des dépendances composer
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Installation de php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Préparation de l'application
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Lancement des tests
        run: php artisan test


