name: Determine and Tag Next Release
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version@2cb40d7a4c1d5b18976a8309e37193ab6d9a2638

  do-the-thing:
    name: Zhu Li, do the thing
    runs-on: ubuntu-latest
    if: needs.get-next-version.outputs.new-release-published == 'true'
    needs:
      - get-next-version

    steps:
      - run: ./do-the-thing ${{ needs.get-next-version.outputs.new-release-version }}
