name: Determine and Tag Next Release
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  determine:
    name: Determine Next Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Important pour récupérer toutes les tags et commits

      - name: Next Semantic-release Version
        uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  next-release:
    name: Next Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && steps.determine.outputs.new-release-published == 'true'
    needs:
      - determine
    steps:
      - run: ./next-release ${{ needs.determine.outputs.new-release-version }}
